### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by theduke** [altdesktop/i3ipc-glib#10]
Hey there,

since the last release was almost a year ago,
and I see commits like a mem leak related one,
please do a new release - better for packaging.

**Comment by acrisci** [comment]
The next release will be a breaking release fyi because of some bugs we found in the library that will change some types, and some breakages in the i3 ipc itself that will change some variable names and types as well. Because of this, I want to take some time for the next release to get everything right. I will work on this during next week and try to have the release done sometime in may.

**Comment by theduke** [comment]
Great, thanks for the heads up.

**Comment by cornerman** [comment]
Please do :)

**Comment by cornerman** [comment]
@acrisci any plans to make a new release?

**Comment by cornerman** [comment]
@acrisci Sorry for taking so long. I have not done any sophisticated tests, but I know that the current master works for all my use-cases and I did not have any problems. But I know that the old version definitely leads to many problems (especially the overflow of window ids). So, I think, releasing the new version is definitely better than keeping it the way it is. Additionally there are some memory leaks in the current release.

**Comment by acrisci** [comment]
Going to start on it this weekend.

Anyone who wants to help can take up an issue on the [2.0 milestone](https://github.com/acrisci/i3ipc-glib/milestone/1).

Will be doing some major surgery.

**Comment by acrisci** [comment]
Going to leave the big stuff to the next release.

https://github.com/altdesktop/i3ipc-glib/releases/tag/v1.0.1
